import { createHash, randomUUID } from 'node:crypto';
import { appendFileSync, chmodSync, existsSync, mkdirSync, readdirSync, renameSync, rmdirSync, statSync, unlinkSync } from 'node:fs';
import path from 'node:path';

export const EXECUTION_TELEMETRY_SCHEMA_VERSION = '1.0.0';
export type TelemetryQuality = 'OBSERVED'|'DERIVED'|'MODELED'|'ASSUMED'|'MISSING'|'NOT_APPLICABLE'|'INVALID';
export type ExecutionEventType = 'CANDIDATE_CREATED'|'DECISION_MADE'|'RISK_ADMISSION'|'MARKET_SNAPSHOT'|'ORDER_SUBMIT_INTENT'|'ORDER_SENT'|'EXCHANGE_ACK'|'EXCHANGE_REJECT'|'FILL_PARTIAL'|'FILL_COMPLETE'|'ORDER_CANCELLED'|'ORDER_EXPIRED'|'POSITION_RECONCILED'|'TRADE_CLOSED'|'TELEMETRY_HEALTH';
export interface ExecutionTelemetryEvent {
  schemaVersion: string; eventId: string; traceId: string; sessionId: string; strategyVersion: string; configHash: string; modelVersion: string;
  symbol: string; side: 'LONG'|'SHORT'|'NONE'; setupType: string; eventType: ExecutionEventType; eventTimestampUtc: string; recordedTimestampUtc: string; source: string;
  candidateId?: string; decisionId?: string; riskAdmissionId?: string; clientOrderId?: string; exchangeOrderId?: string; fillId?: string; positionId?: string;
  quality: Record<string,TelemetryQuality>; data: Record<string,unknown>;
}
export type TelemetryEventDraft = Omit<ExecutionTelemetryEvent,'schemaVersion'|'eventId'|'sessionId'|'strategyVersion'|'configHash'|'modelVersion'|'recordedTimestampUtc'|'eventTimestampUtc'> & Partial<Pick<ExecutionTelemetryEvent,'eventId'|'eventTimestampUtc'>>;
export interface TelemetryHealth { enqueued:number; written:number; dropped:number; invalid:number; writeFailures:number; maxQueueDepth:number; lastError:string|null; overheadMicros:number[]; }
export interface ExecutionTelemetryConfig { enabled:boolean; rootDir:string; sessionId?:string; strategyVersion:string; configHash:string; modelVersion:string; maxQueueSize?:number; maxFileBytes?:number; retentionDays?:number; now?:()=>number; onHealthAlert?:(message:string)=>void; }
const SECRET=/api.?key|secret|signature|authorization|cookie|token|telegram/i;
export function stableTelemetryId(namespace:string,...parts:Array<string|number>):string{return `${namespace}_${createHash('sha256').update(parts.join('|')).digest('hex').slice(0,24)}`;}
export function redactTelemetryValue(value:unknown):unknown { if(Array.isArray(value))return value.map(redactTelemetryValue);if(value&&typeof value==='object'){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>))out[k]=SECRET.test(k)?'[REDACTED]':redactTelemetryValue(v);return out;}return typeof value==='string'&&/(?:api[_-]?key|secret|signature|bearer)\s*[=:]/i.test(value)?'[REDACTED]':value; }
export function validateTelemetryEvent(event:ExecutionTelemetryEvent):string[]{const e:string[]=[];for(const k of ['schemaVersion','eventId','traceId','sessionId','strategyVersion','configHash','modelVersion','symbol','side','setupType','eventType','eventTimestampUtc','recordedTimestampUtc','source'] as const)if(!event[k])e.push(`missing:${k}`);for(const k of ['eventTimestampUtc','recordedTimestampUtc'] as const)if(event[k]&&Number.isNaN(Date.parse(event[k])))e.push(`invalid_timestamp:${k}`);if(JSON.stringify(event).match(SECRET))e.push('secret_like_key_or_value');return e;}
export function sideAwareSlippageBps(side:'BUY'|'SELL',fillPrice:number,referencePrice:number):number{return (side==='BUY'?(fillPrice-referencePrice):(referencePrice-fillPrice))/referencePrice*10_000;}
export function spreadMetrics(bestBid:number,bestAsk:number):{mid:number;spreadPrice:number;spreadBps:number}{if(!(bestAsk>=bestBid&&bestBid>0))throw new Error('invalid bid/ask');const mid=(bestBid+bestAsk)/2;return{mid,spreadPrice:bestAsk-bestBid,spreadBps:(bestAsk-bestBid)/mid*10_000};}

export class ExecutionTelemetry {
 private readonly c:Required<Omit<ExecutionTelemetryConfig,'sessionId'|'onHealthAlert'>> & Pick<ExecutionTelemetryConfig,'onHealthAlert'>; private readonly sessionId:string;private queue:ExecutionTelemetryEvent[]=[];private draining=false;private fileIndex=0;private activeDate='';private activePath='';private closed=false;
 readonly health:TelemetryHealth={enqueued:0,written:0,dropped:0,invalid:0,writeFailures:0,maxQueueDepth:0,lastError:null,overheadMicros:[]};
 constructor(config:ExecutionTelemetryConfig){this.c={...config,maxQueueSize:config.maxQueueSize??5000,maxFileBytes:config.maxFileBytes??25*1024*1024,retentionDays:config.retentionDays??90,now:config.now??Date.now};this.sessionId=config.sessionId??`live-${new Date(this.c.now()).toISOString().replace(/[-:.TZ]/g,'')}-${randomUUID().slice(0,8)}`;if(config.enabled){mkdirSync(config.rootDir,{recursive:true});this.prune();}}
 isEnabled():boolean{return this.c.enabled&&!this.closed;} getSessionId():string{return this.sessionId;}
 emit(draft:TelemetryEventDraft):boolean{if(!this.isEnabled())return true;const start=process.hrtime.bigint();const now=new Date(this.c.now()).toISOString();const event:ExecutionTelemetryEvent={...draft,schemaVersion:EXECUTION_TELEMETRY_SCHEMA_VERSION,eventId:draft.eventId??randomUUID(),sessionId:this.sessionId,strategyVersion:this.c.strategyVersion,configHash:this.c.configHash,modelVersion:this.c.modelVersion,eventTimestampUtc:draft.eventTimestampUtc??now,recordedTimestampUtc:now,data:redactTelemetryValue(draft.data) as Record<string,unknown>};const errors=validateTelemetryEvent(event);if(errors.length){this.health.invalid++;this.alert(`invalid telemetry event: ${errors.join(',')}`);return false;}if(this.queue.length>=this.c.maxQueueSize){this.health.dropped++;this.alert('telemetry queue saturated; event dropped');return false;}this.queue.push(event);this.health.enqueued++;this.health.maxQueueDepth=Math.max(this.health.maxQueueDepth,this.queue.length);if(!this.draining){this.draining=true;setImmediate(()=>this.drain());}this.health.overheadMicros.push(Number(process.hrtime.bigint()-start)/1000);if(this.health.overheadMicros.length>10_000)this.health.overheadMicros.shift();return true;}
 async flush():Promise<void>{while(this.draining||this.queue.length)await new Promise(r=>setTimeout(r,1));}
 async close():Promise<void>{await this.flush();this.closed=true;}
 private drain():void{try{while(this.queue.length){const event=this.queue.shift()!;this.rotateIfNeeded(event.recordedTimestampUtc);appendFileSync(this.activePath,JSON.stringify(event)+'\n',{encoding:'utf8',flag:'a'});this.health.written++;}}catch(err){this.health.writeFailures++;this.health.lastError=(err as Error).message;this.health.dropped+=this.queue.length;this.queue=[];this.alert(`telemetry write failure: ${this.health.lastError}`);}finally{this.draining=false;if(this.queue.length){this.draining=true;setImmediate(()=>this.drain());}}}
 private rotateIfNeeded(iso:string):void{const day=iso.slice(0,10),dir=path.join(this.c.rootDir,day);if(day!==this.activeDate){mkdirSync(dir,{recursive:true});this.activeDate=day;this.fileIndex=0;this.activePath=path.join(dir,`execution-events-${this.sessionId}.jsonl`);}if(existsSync(this.activePath)&&statSync(this.activePath).size>=this.c.maxFileBytes){const rotated=this.activePath.replace('.jsonl',`.${++this.fileIndex}.jsonl`);renameSync(this.activePath,rotated);}try{chmodSync(dir,0o700);if(existsSync(this.activePath))chmodSync(this.activePath,0o600);}catch{/* Windows/unsupported: best effort */}}
 private prune():void{const cutoff=this.c.now()-this.c.retentionDays*86_400_000;for(const name of readdirSync(this.c.rootDir)){if(/^\d{4}-\d{2}-\d{2}$/.test(name)&&Date.parse(`${name}T00:00:00Z`)<cutoff){const dir=path.join(this.c.rootDir,name);for(const file of readdirSync(dir))unlinkSync(path.join(dir,file));try{rmdirSync(dir);}catch{/* best effort */}}}}
 private alert(message:string):void{this.c.onHealthAlert?.(message);}
}
