import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
const root=process.cwd(),data=path.resolve(root,'data'),names=['ZERO_COST','LIGHT','CENTRAL','CONSERVATIVE'] as const;
const readJson=(n:string)=>JSON.parse(readFileSync(path.join(data,`ticket153b-${n.toLowerCase()}-summary.json`),'utf8'));
const zero=readJson('ZERO_COST'),repeat=readJson('ZERO_COST_REPEAT'),runs=names.map(readJson);
const hash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');const esc=(v:unknown)=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};function csv(file:string,rows:Record<string,unknown>[]):void{const h=Object.keys(rows[0]);writeFileSync(path.join(data,file),[h.join(','),...rows.map(r=>h.map(k=>esc(r[k])).join(','))].join('\n'));}
const summary=runs.map(r=>({...r,netPnlDelta:r.netPnl-zero.netPnl,netPnlDeltaPct:zero.netPnl?((r.netPnl-zero.netPnl)/Math.abs(zero.netPnl))*100:0,tradeCountDelta:r.closedTrades-zero.closedTrades,maxDdPctDelta:r.maxDdPct-zero.maxDdPct}));csv('ticket153b-scenario-summary.csv',summary);
csv('ticket153b-cost-decomposition.csv',summary.map(r=>({runId:r.runId,scenario:r.scenario,grossPnl:r.grossPnl,fees:r.feeCost,slippage:r.slippageCost,spread:r.spreadCost,funding:r.fundingCost,other:0,totalExecutionCost:r.totalExecutionCost,netPnl:r.netPnl,reconciliationError:r.grossPnl-r.totalExecutionCost-r.netPnl,tolerance:1e-8,dataQuality:r.dataQuality})));
function parse(file:string){const l=readFileSync(file,'utf8').trim().split(/\r?\n/),h=l.shift()!.split(',');return l.map(x=>Object.fromEntries(x.split(',').map((v,i)=>[h[i],v])))}
const z=parse(path.join(data,'ticket153b-zero_cost-ledger.csv')),zk=new Set(z.map(r=>r.orderId));const recon:Record<string,unknown>[]=[];for(const n of names.slice(1)){const rows=parse(path.join(data,`ticket153b-${n.toLowerCase()}-ledger.csv`)),keys=new Set(rows.map(r=>r.orderId));recon.push({scenario:n,zeroCostOrders:z.length,scenarioOrders:rows.length,exactOrderMatches:[...keys].filter(k=>zk.has(k)).length,missingVersusZero:[...zk].filter(k=>!keys.has(k)).length,extraVersusZero:[...keys].filter(k=>!zk.has(k)).length,explanation:'Declared execution costs change realized balance, which changes risk-pool/margin admission and downstream position paths; strategy code/config/data remain identical.',status:'PASS_WITH_LIMITATIONS',dataQuality:'DQ-B — COMPARABLE_WITH_LIMITATIONS'});}csv('ticket153b-trade-order-reconciliation.csv',recon);
const ohlcv=path.join(data,'ohlcv'),files=readdirSync(ohlcv).filter(f=>f.endsWith('.csv')).sort();const manifest={ticket:'T153B',createdAt:new Date().toISOString(),commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),workingTree:execFileSync('git',['status','--short'],{encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean),node:process.version,determinism:{randomSeed:'NOT_APPLICABLE_NO_RANDOMNESS',zeroCostRepeatExact:JSON.stringify(zero)===JSON.stringify({...repeat,runId:zero.runId,scenario:zero.scenario})},strategyConfigHash:hash(JSON.stringify({matrixV2:true,oodMode:'RISK_REDUCTION',oodThreshold:1.037776,riskReduction:.3,riskDollar:15,riskPoolMaxPct:.15,maxMarginCap:37.5,leverage:30,maxConcurrent:2,t152SameSideGuard:true})),executionSimulator:'executionCostEngine.ts FIXED_BPS/FIXED_TOTAL_BPS',scenarios:summary.map(r=>({runId:r.runId,name:r.scenario,slippageBpsPerSide:r.scenario==='LIGHT'?1:r.scenario==='CENTRAL'?2:r.scenario==='CONSERVATIVE'?5:0,spreadBpsTotal:r.scenario==='LIGHT'?1:r.scenario==='CENTRAL'?2:r.scenario==='CONSERVATIVE'?5:0,takerFeeRate:.0004,latency:'MISSING',funding:'MISSING'})),dataset:Object.fromEntries(files.map(f=>{const p=path.join(ohlcv,f),lines=readFileSync(p,'utf8').trim().split(/\r?\n/);return[f,{sha256:hash(readFileSync(p)),rows:lines.length-1,firstTimestamp:lines[1].split(',')[0],lastTimestamp:lines.at(-1)!.split(',')[0]}]})),models:readdirSync(path.resolve(root,'models')).filter(f=>f.endsWith('.onnx')||f.endsWith('.json')).sort().map(f=>({file:f,sha256:hash(readFileSync(path.resolve(root,'models',f)))})),legacyCheckpoint:{trades:319,label:'DQ-H — HISTORICAL_ONLY',statement:'Historical checkpoint — legacy pre-T152 semantics; not the active comparison baseline.'}};writeFileSync(path.join(data,'ticket153b-run-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
// Dependency-free SVG with common axes.
const curves=names.map(n=>({n,rows:parse(path.join(data,`ticket153b-${n.toLowerCase()}-equity-drawdown.csv`))})),W=1000,H=520,pad=55,maxN=Math.max(...curves.map(c=>c.rows.length)),vals=curves.flatMap(c=>c.rows.map(r=>Number(r.equity))),min=Math.min(...vals),max=Math.max(...vals),colors=['#2563eb','#16a34a','#ea580c','#dc2626'];let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="white"/><text x="${W/2}" y="24" text-anchor="middle" font-family="sans-serif" font-size="18">T153B Equity Curves — Current Production Semantics</text><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="#555"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" stroke="#555"/>`;curves.forEach((c,i)=>{const pts=c.rows.map((r,j)=>`${pad+j/(maxN-1)*(W-2*pad)},${H-pad-(Number(r.equity)-min)/(max-min)*(H-2*pad)}`).join(' ');svg+=`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${pts}"/><text x="${pad+i*210}" y="${H-15}" fill="${colors[i]}" font-family="sans-serif">${c.n}</text>`});svg+=`<text x="8" y="${pad}" font-family="sans-serif">$${max.toFixed(0)}</text><text x="8" y="${H-pad}" font-family="sans-serif">$${min.toFixed(0)}</text></svg>`;writeFileSync(path.join(data,'ticket153b-equity-curves.svg'),svg);
console.log(JSON.stringify({zero,repeat,reconciliation:recon},null,2));
