import {createHash} from 'node:crypto';import {readFileSync,writeFileSync} from 'node:fs';import path from 'node:path';
import {buildBaselineConfig,runReplay,makeFillModel,type ClosedTrade} from './ticket150BacktestExecutionRealismAudit.js';
type Variant='OB_V1_CURRENT'|'OB_V2_LIFECYCLE'|'OB_V2_STRUCTURAL_RETEST'|'OB_V2_STRUCTURAL_RETEST_REWARD'|'OB_DISABLED';type Scenario='FEE_ONLY'|'LIGHT'|'CENTRAL'|'CONSERVATIVE';
const variant=process.env.T157_VARIANT as Variant,scenario=process.env.T157_SCENARIO as Scenario,tag=process.env.T157_TAG??'';if(!variant||!scenario)throw new Error('T157_VARIANT and T157_SCENARIO required');
const costs={FEE_ONLY:[0,0],LIGHT:[1,1],CENTRAL:[2,2],CONSERVATIVE:[5,5]} as const,[slip,spread]=costs[scenario],cfg={...buildBaselineConfig(),sameSideDuplicateGuardEnabled:true};
cfg.entryRouterConfig={...cfg.entryRouterConfig};if(variant==='OB_DISABLED')cfg.entryRouterConfig.obDisabledSymbols=['BTCUSDT','ETHUSDT','SOLUSDT','XRPUSDT'];else if(variant!=='OB_V1_CURRENT'){cfg.entryRouterConfig.obResearchMode=variant as Exclude<Variant,'OB_V1_CURRENT'|'OB_DISABLED'>;cfg.entryRouterConfig.obResearchExpiryBars=Number(process.env.T157_EXPIRY??48) as 24|48|96;cfg.entryRouterConfig.obResearchCentralCostBps=6;if(variant==='OB_V2_STRUCTURAL_RETEST_REWARD')cfg.entryRouterConfig.obSlBufferAtrMultiplier=Number(process.env.T157_BUFFER??.1);}
const out=path.join(process.cwd(),'data'),esc=(v:unknown)=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};function csv(f:string,r:Record<string,unknown>[]){const h=Object.keys(r[0]??{});writeFileSync(path.join(out,f),[h.join(','),...r.map(x=>h.map(k=>esc(x[k])).join(','))].join('\n')+'\n');}
function metric(ts:ClosedTrade[],p:(t:ClosedTrade)=>number){const gp=ts.filter(t=>p(t)>0).reduce((s,t)=>s+p(t),0),gl=-ts.filter(t=>p(t)<0).reduce((s,t)=>s+p(t),0),net=ts.reduce((s,t)=>s+p(t),0);let eq=100,peak=100,dd=0;for(const t of [...ts].sort((a,b)=>a.exitTimestamp-b.exitTimestamp)){eq+=p(t);peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq);}return{trades:ts.length,wins:ts.filter(t=>p(t)>0).length,winRate:ts.length?ts.filter(t=>p(t)>0).length/ts.length*100:0,pf:gl?gp/gl:null,netPnl:net,expectancy:ts.length?net/ts.length:0,maxDd:dd,averageWin:ts.filter(t=>p(t)>0).length?gp/ts.filter(t=>p(t)>0).length:0,averageLoss:ts.filter(t=>p(t)<0).length?-gl/ts.filter(t=>p(t)<0).length:0};}
async function main(){const model=scenario==='FEE_ONLY'?null:makeFillModel(`${variant}-${scenario}`,slip/10000,spread/10000),replay=await runReplay(cfg,model,57833),p=(t:ClosedTrade)=>replay.slippedPnlByEntryTs.get(`${t.symbol}|${t.entryTimestamp}`)??t.pnlUsdTheoretical,rows=replay.trades.map(t=>({variant,scenario,orderId:`${t.symbol}-${t.entryTimestamp}`,symbol:t.symbol,side:t.side,setup:t.setupType,regime:t.regime,entryTimestamp:t.entryTimestamp,exitTimestamp:t.exitTimestamp,entryPrice:t.entryPriceTheoretical,exitPrice:t.exitPriceTheoretical,exitReason:t.exitReason,positionSize:t.positionSize,netPnl:p(t)})),ob=replay.trades.filter(t=>t.setupType==='OB'),summary={variant,scenario,configHash:createHash('sha256').update(JSON.stringify(cfg)).digest('hex'),portfolio:metric(replay.trades,p),ob:metric(ob,p),executionCost:replay.trades.reduce((s,t)=>s+t.pnlUsdTheoretical-p(t),0)+replay.trades.reduce((s,t)=>s+t.positionSize*cfg.takerFeeRate*2,0),productionBehaviorModified:false};csv(`ticket157-${variant.toLowerCase()}-${scenario.toLowerCase()}-ledger.csv`,rows);writeFileSync(path.join(out,`ticket157-${variant.toLowerCase()}-${scenario.toLowerCase()}-summary.json`),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary));}main().catch(e=>{console.error(e);process.exit(1)});
