import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { validateTelemetryEvent, type ExecutionTelemetryEvent } from '../dist/live/executionTelemetry.js';
const inputArg=process.argv.find(a=>a.startsWith('--input='))?.slice(8);if(!inputArg)throw new Error('Usage: --input=<jsonl> [--export=<sanitized.jsonl>]');
const input=path.resolve(process.cwd(),inputArg),exportArg=process.argv.find(a=>a.startsWith('--export='))?.slice(9);const lines=readFileSync(input,'utf8').split(/\r?\n/).filter(Boolean);const events:ExecutionTelemetryEvent[]=[];let invalidJson=0;for(const line of lines){try{events.push(JSON.parse(line));}catch{invalidJson++;}}
const validationErrors=events.flatMap(e=>validateTelemetryEvent(e).map(error=>({eventId:e.eventId,error}))),ids=new Set<string>(),duplicateIds:string[]=[];for(const e of events){if(ids.has(e.eventId))duplicateIds.push(e.eventId);ids.add(e.eventId);}const byTrace=new Map<string,ExecutionTelemetryEvent[]>();for(const e of events)byTrace.set(e.traceId,[...(byTrace.get(e.traceId)??[]),e]);
const traces=[...byTrace.values()],has=(t:ExecutionTelemetryEvent[],type:string)=>t.some(e=>e.eventType===type),ratio=(a:number,b:number)=>b? a/b:null;const candidates=traces.filter(t=>has(t,'CANDIDATE_CREATED')),allowed=traces.filter(t=>t.some(e=>e.eventType==='DECISION_MADE'&&e.data.decision==='ALLOW')),intents=traces.filter(t=>has(t,'ORDER_SUBMIT_INTENT')),orders=traces.filter(t=>has(t,'EXCHANGE_ACK')||has(t,'EXCHANGE_REJECT')),filled=traces.filter(t=>has(t,'FILL_PARTIAL')||has(t,'FILL_COMPLETE')),closed=traces.filter(t=>has(t,'TRADE_CLOSED'));const quoteEvents=events.filter(e=>e.eventType==='MARKET_SNAPSHOT'),fees=events.filter(e=>e.eventType.startsWith('FILL_')),reconciles=events.filter(e=>e.eventType==='POSITION_RECONCILED');
const negativeDurations=events.filter(e=>Date.parse(e.recordedTimestampUtc)<Date.parse(e.eventTimestampUtc)).length;const metrics={input,events:events.length,traces:traces.length,candidateToDecision:ratio(candidates.filter(t=>has(t,'DECISION_MADE')).length,candidates.length),allowedDecisionToIntent:ratio(allowed.filter(t=>has(t,'ORDER_SUBMIT_INTENT')).length,allowed.length),intentToExchangeOrder:ratio(intents.filter(t=>has(t,'EXCHANGE_ACK')||has(t,'EXCHANGE_REJECT')).length,intents.length),exchangeOrderToTerminal:ratio(orders.filter(t=>has(t,'FILL_COMPLETE')||has(t,'EXCHANGE_REJECT')||has(t,'ORDER_CANCELLED')||has(t,'ORDER_EXPIRED')).length,orders.length),filledOrderToFillLedger:ratio(filled.filter(t=>t.some(e=>Boolean(e.fillId))).length,filled.length),closedTradeToEntryExitFills:ratio(closed.filter(t=>t.filter(e=>e.eventType.startsWith('FILL_')).length>=2).length,closed.length),quoteCoverage:ratio(quoteEvents.filter(e=>e.quality.bestBid==='OBSERVED'&&e.quality.bestAsk==='OBSERVED').length,quoteEvents.length),feeCoverage:ratio(fees.filter(e=>e.quality.commission==='OBSERVED').length,fees.length),fundingCoverage:ratio(closed.filter(t=>t.some(e=>e.quality.funding==='OBSERVED')).length,closed.length),reconciliationMatchRate:ratio(reconciles.filter(e=>e.data.status==='MATCH').length,reconciles.length),invalidJson,validationErrorCount:validationErrors.length,duplicateEventIdCount:duplicateIds.length,negativeDurationCount:negativeDurations};
const complete=metrics.candidateToDecision===1&&metrics.allowedDecisionToIntent===1&&metrics.intentToExchangeOrder===1&&metrics.exchangeOrderToTerminal===1&&metrics.filledOrderToFillLedger===1&&metrics.closedTradeToEntryExitFills===1&&metrics.quoteCoverage===1&&metrics.feeCoverage===1;const label=invalidJson||validationErrors.length||duplicateIds.length||negativeDurations?'CAL-F — INVALID_EXPORT':complete?'CAL-A — CALIBRATION_READY':events.length?'CAL-C — DIAGNOSTIC_ONLY':'CAL-F — INVALID_EXPORT';const report={schemaVersion:'1.0.0',datasetLabel:label,metrics,validationErrors,duplicateIds};writeFileSync(path.resolve(process.cwd(),'data/ticket154-validation-report.json'),JSON.stringify(report,null,2)+'\n');
if(exportArg){const h=(s:string)=>createHash('sha256').update(s).digest('hex').slice(0,20);const sanitized=events.map(e=>({...e,eventId:h(e.eventId),traceId:h(e.traceId),sessionId:h(e.sessionId),candidateId:e.candidateId?h(e.candidateId):undefined,decisionId:e.decisionId?h(e.decisionId):undefined,riskAdmissionId:e.riskAdmissionId?h(e.riskAdmissionId):undefined,clientOrderId:e.clientOrderId?h(e.clientOrderId):undefined,exchangeOrderId:e.exchangeOrderId?h(e.exchangeOrderId):undefined,fillId:e.fillId?h(e.fillId):undefined,positionId:e.positionId?h(e.positionId):undefined}));writeFileSync(path.resolve(process.cwd(),exportArg),sanitized.map(e=>JSON.stringify(e)).join('\n')+'\n');}
console.log(JSON.stringify(report,null,2));
